### ISSUE TITLE
DPL-1063 - As a developer I need to create a table to store aliquots to track library volumes and enable top-up management

### ISSUE THREAD

**Issue by stevieing** [sanger/unified_warehouse#582]
**User story**
As a developer I need to create a table to store aliquots to track sample volumes and enable top-up management

NB This story will need to be refined again due to the multiplexing changes.

**Who are the primary contacts for this story**
Steve / Ben

**Who is the nominated tester for UAT**
Steve / Ben

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] an aliquots table
- [x] a lims source attribute
- [x] a lims uuid attribute
- [x] an aliquot type attribute
- [x] a source type attribute
- [x] a source barcode attribute
- [x] a sample name attribute
- [x] a used by type attribute
- [x] a used by barcode attribute
- [x] a volume attribute

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- sanger/traction-service#1186
- sanger/traction-service#1136

**Additional context**
The fields may be subject to change based on need and refactoring of other areas e.g. multiplexing.

**Comment by BenTopping** [comment]
Worth considering if we want to back fill this with all our aliquots created from old data. It may not be accurate with volume but could be useful for reporting.

**Comment by dasunpubudumal** [comment]
@stevieing @BenTopping do you think that a `recorded_at` attribute (with/or a `last_updated` attribute) would be beneficial here? Just suggesting since such attribute is not mentioned in the story. It might be worthwhile perhaps as a version number for optimistic locking (if a need for such case arises).
