### ISSUE TITLE
Y24-350 - As developers we want to enforce constraints in the sample table so that duplicates cannot break the downstream analysis systems

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/unified_warehouse#682]
**User story**
As developers we want to enforce a unique constraint across the _id_lims_ and _id_sample_lims_ columns in the _sample_ table so that duplicates cannot break the downstream analysis systems.

**Who are the primary contacts for this story**
TW DJ SI

**Who is the nominated tester for UAT**
This can be tested internally by the team attempting to insert records that violate the constraint.

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] enforce a unique constraint across the id_lims and id_sample_lims columns in the sample table 
- [ ] add an index on id_lims, id_sample_lims
- [ ] Add a NOT NULL constraint to the uuid_sample_lims column
- [ ] Existing production and UAT data in the sample table is checked and if required modified to be consistent with the new constraint.
- [ ] NPG and MLWH stakeholders (see Confluence) are notified of the change.
- [ ] DBA team are contacted and review change before deployment to production environment.

**Additional context**
The MLWH has always been intended to support multiple LIMS systems. However, uniqueness of sample ids within each lims system has never been enforced.
The downstream analysis pipeline maintained by NPG is currently being modified to support the possibility of duplicate id_sample_lims across _different_ LIMS systems in the table. 
However, the downstream analysis system will fail or worse associate sequencing data with the wrong sample if id_sample_lims is not unique with a give id_lims. To avoid that we want to enforce that uniqueness in the database.

**Comment by stevieing** [comment]
Check for any instances where constraints could be broken:

```
duplicate_id_sample_lims = Sample.select(:id_sample_lims)
                      .group(:id_sample_lims)
                      .having('COUNT(*) > 1')
                      .pluck(:id_sample_lims)

empty_uuid_sample_lims = Sample.where(uuid_sample_lims: nil).pluck(:id_sample_lims)   
```
