### ISSUE TITLE
Y24-488 - As a developer (Ben) I would like to update the way the Aliquot table accepts data so that aliquot updates can be correctly reflected.

### ISSUE THREAD

**Issue by BenTopping** [sanger/unified_warehouse#699]
**User story**

As a developer (Ben) I would like to update the way the Aliquot table accepts data so that aliquot updates can be correctly reflected. In the current implementation we only create a record if there is a new UUID for the aliquot. However Traction does not change the UUID if an existing aliquot's data changes, for example a volume update, in which case the aliquot is not created in the warehouse.

In the new implementation we would like the Aliquot table to create a new record if ANY of its values change. This allows us to create new records for aliquot updates and it maintains an audit of updates.

**Who are the primary contacts for this story**
Ben T, Seena N, Steve I

**Acceptance criteria**

Consider if these features can be _featured flagged_ to decouple testing and deployment.
To be considered successful the solution must allow:
- [ ] Aliquot table creates a new record if an existing aliquot has updated data
- [ ] Aliquot table does not create a new record if an existing aliquot has no updated data.
- [ ] Nuke the existing table data.
- [ ] Repopulate the data via Traction rake task.

**Additional context**
This came out of research into the Aliquot table behaviour during https://github.com/sanger/traction-service/issues/1458 when attempting to update values was causing issues.
